### ISSUE TITLE
[Feature] Add Readline capabilities

### ISSUE THREAD

**Issue by FredPraca** [pyjarrett/septum#9]
As an enhancement for interactive mode, using _GNATCOLL.Readline_ would be great.

**Comment by pyjarrett** [comment]
GNATCOLL.Readline looks like a good *nix solution.  It doesn't look like it's available on Windows, but this looks doable with the [Windows Console API](https://docs.microsoft.com/en-us/windows/console/).

**Comment by pyjarrett** [comment]
Mostly working in 352229a4c896bd079b1d321588006d9686d5733c.  It requires an unpublished version of Trendy_Terminal and I'm still testing, so not closing this yet.

**Comment by pyjarrett** [comment]
There's enough features implemented that this should be closed, with enhancements tracked separately.
